# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-24 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
