# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-24 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_external_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
    ]
