# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='pub_date',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='_', max_length=40),
            preserve_default=False,
        ),
    ]
